import iopulsenet
import glob
import argparse
import os
import sys
import matplotlib.pyplot as plt
import numpy as np
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='CNN classifier')
    parser.add_argument('-d', nargs=1, default=["/home/kawahara/VI/train1/data"],help='directory containing train sets generated by gtls_mockkepler.', type=str)

    import datetime    
    args = parser.parse_args()
    traindir=args.d[0]
    flist=sorted(glob.glob(os.path.join(traindir,'*.npz')))

    for fn in flist:
        d=np.load(fn,allow_pickle=True)
        fig=plt.figure()
        ax=fig.add_subplot(411)
        plt.title("label"+str(d["arr_0"][0]))
        ax.plot(d["arr_1"]+1.0,label="1")
        ax=fig.add_subplot(412)
        ax.plot(d["arr_2"]+1.0,label="2")
        
        ax2=fig.add_subplot(413)        
        ax2.plot(d["arr_3"]+1.0,label="3")
        ax2.plot(d["arr_5"]+0.5,label="5")
        ax2.plot(d["arr_7"]+1.0,label="7")
        ax2.plot(d["arr_9"]+1.0,label="9")
        plt.legend()
        ax2=fig.add_subplot(414)        
        ax2.plot(d["arr_4"]+1.0,label="4")
        ax2.plot(d["arr_6"]+0.5,label="6")
        ax2.plot(d["arr_8"]+1.0,label="8")
        ax2.plot(d["arr_10"]+1.0,label="10")
        plt.legend()

        #        Xw.append(np.array([d["arr_2"]+1.0,d["arr_4"]+1.0,d["arr_6"]+0.5,d["arr_8"]+1.0,d["arr_10"]+1.0]).T)
        plt.show()
        plt.close()
